### Inregistrare
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
  "nume": "Eduard",
  "email": "eduard@test.com",
  "parola": "parola123"
}

### Login
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "email": "eduard@test.com",
  "parola": "parolaNoua456"
}